#!/usr/bin/env bash
# Sync the widget sources from the model repo into this deploy repo's src/ tree and
# regenerate app_files.js (the manifest index.html mounts into the stlite filesystem).
#
# Usage:  deploy/sync.sh [path-to-model-repo-widget-dir]
# Then:   git add -A && git commit -m "sync widget" && git push
set -euo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
SRC="${1:-/Users/macbook/Library/CloudStorage/GoogleDrive-pakocica@gmail.com/My Drive/Projects/CAIS_Fellowship/Project/model/widget}"

[ -f "$SRC/app.py" ] || { echo "error: $SRC does not look like the widget dir (no app.py)"; exit 1; }

rm -rf "$REPO/src"
mkdir -p "$REPO/src/ui" "$REPO/src/mc_component"
cp "$SRC/app.py" "$SRC/notebook_loader.py" "$SRC/model_notebook.ipynb" "$REPO/src/"
cp "$SRC"/ui/*.py "$REPO/src/ui/"
cp "$SRC/mc_component/index.html" "$REPO/src/mc_component/"

# Manifest: every file under src/, as repo-relative paths. index.html fetches each by URL
# and mounts it at the same path (minus the src/ prefix) in the in-browser filesystem.
{
  echo "// generated by deploy/sync.sh — do not edit by hand"
  echo "export const APP_FILES = ["
  (cd "$REPO" && find src -type f ! -name '.DS_Store' | LC_ALL=C sort | sed 's/.*/  "&",/')
  echo "];"
} > "$REPO/app_files.js"

# Guard: the host layer — index.html and the loading intro (intro.js/intro.css) — lives
# at the repo ROOT, outside src/, and this script must never touch it. Fail loudly if any
# of it has gone missing so a bad sync can't silently ship a page without the intro.
for f in index.html intro.js intro.css; do
  [ -f "$REPO/$f" ] || { echo "error: $REPO/$f is missing — the root host/intro layer was clobbered; restore it before pushing"; exit 1; }
done

echo "synced from: $SRC"
(cd "$REPO" && git status --short) || true
